T_gauss = readtable("../data/gaussian_test/data100_L0.25_Lp0.25_m200_testall_M85_level6.csv");
T_pca = readtable("../data/gaussian_test/data100_L0.25_Lp0.25_m200_testall_PCA_M85.csv");

%T_gauss = readtable("../data/gaussian_test/data1000_L0.25_Lp0.25_testall_M85_level6.csv");
%T_pca = readtable("../data/gaussian_test/data1000_L0.25_Lp0.25_testall_PCA_M85.csv");

heights = unique(T_pca{:,"gauss_height"});
%heights = heights(2:end);

detect_pca = [];
detect_gauss = [];
local_gauss = [];

for i = 1:length(heights)
    height = heights(i);

    detect = T_pca{T_pca.gauss_height == height,"detect"};
    detect_pca = cat(1, detect_pca, mean(detect));

    detect = T_gauss(T_gauss.gauss_height == height,:);
    ds = [];
    ls = [];

    for j = 1:size(detect,1)
        d = 0;
        l =-1;
        for level = 0:6
            if detect{j,"detect_"+level} == 1
                d = 1;
                if detect{j,"local_"+level} == 1
                    l = level;
                end
            end
        end
        ds = cat(1,ds,d);
            if l > -1
                ls = cat(1,ls,l);
            end
    end
    detect_gauss = cat(1, detect_gauss, mean(ds));
    local_gauss = cat(1, local_gauss, mean(ls));
end

set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

colormaps = [[143 188 143]/255; [1 0.5 0.2]; [30 144 255]/255; [119,136,153]/256];

lw = 2;

% Figure comparing detection statistics across 2 models
figure('Name', "Figure 1", 'Units', 'Pixels', 'Position', [100 100 600 450]);

hold on;
vline = plot(heights, detect_gauss, '-o');
set(vline,...
        "DisplayName", "KL",...
        "Color", colormaps(3,:),...
        'LineWidth', 2,...
        'MarkerFaceColor', 'w');

pline = plot(heights, detect_pca, '-o');
set(pline,...
        "DisplayName", "PCA",...
        "Color", colormaps(2,:),...
        'LineWidth', 2,...
        'MarkerFaceColor', 'w');

yv = yline(detect_gauss(1),'--','KL False Positive Rate');
set(yv,...
    "Color", colormaps(3,:),...
    'LineWidth', 2,...
    'HandleVisibility', 'off');

yp = yline(detect_pca(1),'--','PCA False Positive Rate');
set(yp,...
    "Color", colormaps(2,:),...
    'LineWidth', lw,...
    'HandleVisibility', 'off');

legend('Location', 'best');
hold off;
xlim([0,0.2]);
xscale("log");
ylim([-0.05,1.05]);

hTitle  = title("Detection Rate vs. Gaussian Height");
hXLabel = xlabel('Gaussian Height'                  );
hYLabel = ylabel('Detection Rate'                   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 15          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.25:1, ...
  'LineWidth'   , 1         );


% Figure showing mean localization as a function of Gaussian Height
figure('Name', "Figure 2", 'Units', 'Pixels', 'Position', [100 100 600 450]);

local_idx = ~isnan(local_gauss);
vline = plot(heights(local_idx), local_gauss(local_idx), '-o');
set(vline,...
        "DisplayName", "KL",...
        "Color", colormaps(3,:),...
        'LineWidth', lw,...
        'MarkerFaceColor', 'w');
xlim([0,0.2]);
ylim([0,6]);
xscale("log");

hTitle  = title("KL Mean Localization Level vs. Gaussian Height");
hXLabel = xlabel('Gaussian Height'                  );
hYLabel = ylabel('Mean Localization Level'                   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 15          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:1:6, ...
  'LineWidth'   , 1         );


clouds = [1,15,24];
len = 200;
spe = T_pca{:,"spe"};
fig = figure('Name', "Figure 3", 'Units', 'Pixels', 'Position', [100 100 600 450]);
hold("on");
for i = 1:length(clouds)
    idx = clouds(i);
    scatter(1+(i-1)*len+(i-1)*len/8:i*len+(i-1)*len/8, spe(1+(idx-1)*len:idx*len), 10, colormaps(i,:),'filled');
end
legend('No Gaussian', 'Gaussian Height 0.01.', 'Gaussian Height 0.1', 'Location', 'west');
hold("off")
%thresh = yline(0.1293, '--','Q-stat Threshold');
thresh = yline(1.4743, '--','Q-stat Threshold');
set(thresh,...
    'LineWidth', 1.5,...
    'HandleVisibility', 'off');

%thresh_1 = yline(0.0306, '--','Optimal Threshold');
thresh_1 = yline(0.1376, '--','Optimal Threshold');
set(thresh_1,...
    'LineWidth', 1.5,...
    'Color', 'red',...
    'HandleVisibility', 'off');

hTitle  = title("PCA Squared Prediction Error (SPE) of Test Samples");
hYLabel = ylabel('SPE'                   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hYLabel], ...
    'FontName'   , 'AvantGarde');
set(hYLabel, ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 15          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.25:1, ...
  'LineWidth'   , 1         );