load('../data/sentinel_eig.mat')
sent_lambda = lambda;
load('../data/gauss_eig_2.mat')
gauss_lambda =  lambda;

set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

colormaps = [[143 188 143]/255; [1 0.5 0.2]; [30 144 255]/255; [119,136,153]/256];

% Figure comparing detection statistics across 2 models
figure('Name', "Figure 1", 'Units', 'Pixels', 'Position', [100 100 600 450]);

filtered_lambda = sent_lambda(sent_lambda > 1e-10);
scatter(1:length(filtered_lambda), filtered_lambda', 16, colormaps(2,:), 'filled');
yscale("log");

xv = xline(60,'--','Truncation Point');
set(xv,...
    "Color", colormaps(3,:),...
    'LineWidth', 2,...
    'HandleVisibility', 'off');

yticks(10.^(-2:6)); 

%xlim([0,0.2]);
%ylim([-0.05,1.05]);

hTitle  = title("Eigenvalues of KL Expansion");
%hXLabel = xlabel('Eigenvalue Number'                  );
hYLabel = ylabel('Eigenvalue'                   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hYLabel], ...
    'FontName'   , 'AvantGarde');
set(hYLabel  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 15          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'YMinorGrid'  , 'off'     , ...
  'YTick'       , [1e-2, 1e-1, 1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6] , ...
  'LineWidth'   , 1);


figure('Name', "Figure 2", 'Units', 'Pixels', 'Position', [100 100 600 450]);

filtered_lambda = gauss_lambda(gauss_lambda > 1e-10);
scatter(1:length(filtered_lambda), filtered_lambda', 12, colormaps(3,:), 'filled');
yscale("log");

yv = yline(detect_gauss(1),'--','KL False Positive Rate');
set(yv,...
    "Color", colormaps(3,:),...
    'LineWidth', 2,...
    'HandleVisibility', 'off');

%xlim([0,0.2]);
%ylim([-0.05,1.05]);

hTitle  = title("Eigenvalues of KL Expansion");
%hXLabel = xlabel('Eigenvalue Number'                  );
hYLabel = ylabel('Eigenvalue'                   );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hYLabel], ...
    'FontName'   , 'AvantGarde');
set(hYLabel  , ...
    'FontSize'   , 14          );
set( hTitle                    , ...
    'FontSize'   , 15          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3]);